import React, { useEffect, useState } from 'react';
import { api } from './api';

export default function Communications({ event }) {
  const [history, setHistory] = useState([]), [people, setPeople] = useState([]), [selected, setSelected] = useState([]), [filter, setFilter] = useState('approved'), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  const path = `/platform/organizer/events/${event.id}/communications`;
  useEffect(() => { let active = true, reading = false; const refresh = async () => { if (reading) return; reading = true; try { const [mail, attendance] = await Promise.all([api(path), api(`/platform/organizer/events/${event.id}/attendance`)]); if (active) { setHistory(mail.messages); setPeople(attendance.attendees); } } catch (issue) { if (active) setError(issue.message); } finally { reading = false; } }; refresh(); const timer = setInterval(refresh, 5000); return () => { active = false; clearInterval(timer); }; }, [event.id]);
  async function send(body) { if (busy) return; setBusy(true); setError(''); try { const result = await api(path, { method: 'POST', body }); setMessage(result.message); setHistory((await api(path)).messages); return true; } catch (issue) { setError(issue.message); } finally { setBusy(false); } }
  async function invite(e) { e.preventDefault(); const form = e.currentTarget, emails = new FormData(form).get('emails').split(/[\s,;]+/).filter(Boolean); if (await send({ action: 'invite', emails })) form.reset(); }
  async function announce(e) { e.preventDefault(); const form = e.currentTarget, data = Object.fromEntries(new FormData(form)); if (await send({ ...data, recipients: selected })) { form.reset(); setSelected([]); } }
  const shown = people.filter(person => filter === 'all' || (person.registrationStatus || 'approved') === filter);
  return <div className="communications-page"><a href="#workspace" className="text-link">← Your events</a><p className="eyebrow">{event.name} / COMMUNICATIONS</p><h1 className="display-title">KEEP THEM <span className="orange">IN THE LOOP.</span></h1><div className="communications-grid"><section className="registration-form"><h2>Invite your guests.</h2><p>Guest invitations reserve no places. The invited email must match the registration. Approval requirements are waived for an invited guest; capacity still applies.</p><form onSubmit={invite}><label>Email addresses<textarea name="emails" rows="5" required maxLength="6500" placeholder="one@example.com&#10;two@example.com"/><small>Up to 25 addresses, separated by commas or new lines.</small></label><button className="primary" disabled={busy}>Queue guest invitations</button></form></section><section className="registration-form"><h2>Send an announcement.</h2><form onSubmit={announce}><label>Subject<input name="subject" required maxLength="120"/></label><label>Message<textarea name="message" required rows="5" maxLength="3000"/></label><label>Show guests<select value={filter} onChange={e => setFilter(e.target.value)}>{['approved', 'pending', 'waitlisted', 'declined', 'cancelled', 'all'].map(value => <option key={value}>{value}</option>)}</select></label><div className="recipient-list">{shown.map(person => <label className="checkbox" key={person.id}><input type="checkbox" checked={selected.includes(person.id)} onChange={e => setSelected(current => e.target.checked ? [...current, person.id] : current.filter(id => id !== person.id))}/><span>{person.name}<small>{person.email} · {person.registrationStatus || 'approved'}</small></span></label>)}{!shown.length && <p>No guests in this group.</p>}</div><p>{selected.length} recipients selected. Maximum 50 per announcement.</p><button className="primary" disabled={busy || !selected.length || selected.length > 50}>Queue announcement</button></form></section></div><p role="status">{message}</p>{error && <p role="alert">{error}</p>}<div className="list-heading"><h2>Delivery activity</h2><button className="text-link" disabled={busy} onClick={() => send({ action: 'resume' })}>Resume queued messages</button></div><p className="muted">“Accepted” means Gmail accepted the email, not that it arrived in an inbox. Messages share the existing sending allowance.</p><table><caption className="sr-only">Event email activity</caption><thead><tr><th>Recipient</th><th>Subject</th><th>Type</th><th>Status</th></tr></thead><tbody>{history.map(mail => <tr key={mail.id}><td>{mail.email}</td><td>{mail.subject}</td><td>{mail.kind}</td><td>{mail.mailState === 'sending' ? 'Sending / awaiting confirmation' : mail.mailState === 'skipped_test_recipient' ? 'No email sent (test address)' : mail.mailState}</td></tr>)}</tbody></table>{!history.length && <p>No messages yet.</p>}</div>;
}
